# Data Exploration - AIF360

raw data instead of dataset from lib
* H251 --> most recent dataset (2023) 
* H243 --> second most recent dataset (2022)

https://github.com/Trusted-AI/AIF360

In [81]:
"""
    in case we use aif360 MEPSdataset19 -> do pip installs
    i didn't use it because the data was older
    i chose the most recent data which i had to download raw xlxs file
    and then convert to csv
        - h252
        - h243 -> i didnt use it, but we could, it has same structure
"""
# %pip install 'aif360[all]'
# %pip install fairlearn

"\n    in case we use aif360 MEPSdataset19 -> do pip installs\n    i didn't use it because the data was older\n    i chose the most recent data which i had to download raw xlxs file\n    and then convert to csv\n        - h252\n        - h243 -> i didnt use it, but we could, it has same structure\n"

# General Imports

In [82]:
import pandas as pd
import numpy as np

In [83]:
# data_h243 = pd.read_csv('h243.csv')

# display(data_h243.head())
# print(data_h243.columns.tolist())

# print("\n" + "===="* 10 + "\n")

data_h251 = pd.read_csv('h251.csv')

display(data_h251.head())
print(data_h251.columns.tolist())

,DUID,PID,DUPERSID,PANEL,DATAYEAR,FAMID31,FAMID42,FAMID53,FAMID23,FAMIDYR,...,RXWCP23,RXOSR23,RXPTR23,RXOTH23,PERWT23F,FAMWT23F,FAMWT23C,SAQWT23F,VARSTR,VARPSU
0,2790002,101,2790002101,27,2023,A,A,A,A,A,...,0,0,82,0,11664.42682,11158.81783,11158.81783,13221.31567,2019,1
1,2790002,102,2790002102,27,2023,A,A,A,A,A,...,0,0,0,0,32212.11360,11158.81783,11158.81783,0.00000,2019,1
2,2790004,101,2790004101,27,2023,A,A,A,A,A,...,0,0,0,0,21944.14283,28540.74594,28540.74594,29999.27748,2084,1
3,2790006,101,2790006101,27,2023,A,A,A,A,A,...,0,0,0,0,10328.00953,10821.04069,10821.04069,11144.51392,2113,1
4,2790006,102,2790006102,27,2023,A,A,A,A,A,...,0,0,0,0,17430.52136,10821.04069,10821.04069,0.00000,2113,1

['DUID', 'PID', 'DUPERSID', 'PANEL', 'DATAYEAR', 'FAMID31', 'FAMID42', 'FAMID53', 'FAMID23', 'FAMIDYR', 'CPSFAMID', 'FCSZ1231', 'FCRP1231', 'RULETR31', 'RULETR42', 'RULETR53', 'RULETR23', 'RUSIZE31', 'RUSIZE42', 'RUSIZE53', 'RUSIZE23', 'RUCLAS31', 'RUCLAS42', 'RUCLAS53', 'RUCLAS23', 'FAMSZE31', 'FAMSZE42', 'FAMSZE53', 'FAMSZE23', 'FMRS1231', 'FAMS1231', 'FAMSZEYR', 'FAMRFPYR', 'REGION31', 'REGION42', 'REGION53', 'REGION23', 'REFPRS31', 'REFPRS42', 'REFPRS53', 'REFPRS23', 'RESP31', 'RESP42', 'RESP53', 'RESP23', 'PROXY31', 'PROXY42', 'PROXY53', 'PROXY23', 'INTVLANG', 'INTVTYPE31', 'INTVTYPE42', 'INTVTYPE53', 'BEGRFM31', 'BEGRFY31', 'ENDRFM31', 'ENDRFY31', 'BEGRFM42', 'BEGRFY42', 'ENDRFM42', 'ENDRFY42', 'BEGRFM53', 'BEGRFY53', 'ENDRFM53', 'ENDRFY53', 'ENDRFM23', 'ENDRFY23', 'KEYNESS', 'INSCOP31', 'INSCOP42', 'INSCOP53', 'INSCOP23', 'INSC1231', 'INSCOPE', 'ELGRND31', 'ELGRND42', 'ELGRND53', 'ELGRND23', 'PSTATS31', 'PSTATS42', 'PSTATS53', 'RURSLT31', 'RURSLT42', 'RURSLT53', 'AGE31X', 'AGE42X', 'AGE53X', 'AGE23X', 'AGELAST', 'DOBMM', 'DOBYY', 'SEX', 'RACEV1X', 'RACEV2X', 'RACEAX', 'RACEBX', 'RACEWX', 'RACETHX', 'HISPANX', 'HISPNCAT', 'MARRY31X', 'MARRY42X', 'MARRY53X', 'MARRY23X', 'SPOUID31', 'SPOUID42', 'SPOUID53', 'SPOUID23', 'SPOUIN31', 'SPOUIN42', 'SPOUIN53', 'SPOUIN23', 'EDUCYR', 'HIDEG', 'FTSTU31X', 'FTSTU42X', 'FTSTU53X', 'FTSTU23X', 'ACTDTY31', 'ACTDTY42', 'ACTDTY53', 'EVERSERVED', 'REFRL31X', 'REFRL42X', 'REFRL53X', 'REFRL23X', 'OTHLGSPK', 'WHTLGSPK', 'HWELLSPK', 'BORNUSA', 'YRSINUS', 'MOPID31X', 'MOPID42X', 'MOPID53X', 'DAPID31X', 'DAPID42X', 'DAPID53X', 'HIBPDX', 'HIBPAGED', 'BPMLDX', 'CHDDX', 'CHDAGED', 'ANGIDX', 'ANGIAGED', 'MIDX', 'MIAGED', 'OHRTDX', 'OHRTAGED', 'OHRTTYPE', 'STRKDX', 'STRKAGED', 'EMPHDX', 'EMPHAGED', 'CHBRON31', 'CHOLDX', 'CHOLAGED', 'CANCERDX', 'CABLADDR', 'CABREAST', 'CACERVIX', 'CACOLON', 'CALUNG', 'CALYMPH', 'CAMELANO', 'CAOTHER', 'CAPROSTA', 'CASKINNM', 'CASKINDK', 'CAUTERUS', 'DIABDX_M18', 'DIABAGED', 'JTPAIN31_M18', 'ARTHDX', 'ARTHTYPE', 'ARTHAGED', 'ASTHDX', 'ASTHAGED', 'ASSTIL31', 'ASATAK31', 'ASTHEP31', 'ASACUT31', 'ASMRCN31', 'ASPREV31', 'ASDALY31', 'ASPKFL31', 'ASEVFL31', 'ASWNFL31', 'ADHDADDX', 'ADHDAGED', 'COVIDEVER31', 'COVIDEVER53', 'LCEVER31', 'LCEVER53', 'COVSYMNOW31', 'COVSYMNOW53', 'COVREDABIL31', 'COVREDABIL53', 'COVID12MO31', 'COVID12MO53', 'COVMNTHX31', 'COVMNTHX53', 'COVYRDX31', 'COVYRDX53', 'RTHLTH31', 'RTHLTH42', 'RTHLTH53', 'MNHLTH31', 'MNHLTH42', 'MNHLTH53', 'IADLHP31', 'ADLHLP31', 'AIDHLP31', 'WLKLIM31', 'LFTDIF31', 'STPDIF31', 'WLKDIF31', 'MILDIF31', 'STNDIF31', 'BENDIF31', 'RCHDIF31', 'FNGRDF31', 'ACTLIM31', 'WRKLIM31', 'HSELIM31', 'SCHLIM31', 'UNABLE31', 'SOCLIM31', 'COGLIM31', 'DFHEAR42', 'DFSEE42', 'DFCOG42', 'DFWLKC42', 'DFDRSB42', 'DFERND42', 'ANYLMI23', 'CHPMED42', 'CHPMHB42', 'CHPMCN42', 'CHSERV42', 'CHSRHB42', 'CHSRCN42', 'CHLIMI42', 'CHLIHB42', 'CHLICO42', 'CHTHER42', 'CHTHHB42', 'CHTHCO42', 'CHCOUN42', 'CHEMPB42', 'CSHCN42', 'GETTRB42', 'MOMPRO42', 'DADPRO42', 'UNHAP42', 'SCHLBH42', 'HAVFUN42', 'ADUPRO42', 'NERVAF42', 'SIBPRO42', 'KIDPRO42', 'SPRPRO42', 'SCHPRO42', 'HOMEBH42', 'CHILCR42', 'CHILWW42', 'CHRTCR42', 'CHRTWW42', 'CHAPPT42', 'CHLIST42', 'CHEXPL42', 'CHRESP42', 'CHPRTM42', 'CHHECR42', 'CHSPEC42_M18', 'CHEYRE42_M18', 'LSTETH53', 'PHYEXE53', 'OFTSMK53', 'COVAXEVR31', 'COVAXEVR42', 'COVAXEVR53', 'COVAXNEW31', 'COVAXNEW42', 'COVAXNEW53', 'SAQELIG', 'ADPROX42', 'ADGENH42', 'ADDAYA42', 'ADCLIM42', 'ADACLS42', 'ADWKLM42', 'ADEMLS42', 'ADMWCF42', 'ADPAIN42', 'ADPCFL42', 'ADENGY42', 'ADPRST42', 'ADSOCA42', 'ADNERV42', 'ADHOPE42', 'ADREST42', 'ADSAD42', 'ADEFRT42', 'ADWRTH42', 'K6SUM42', 'ADINTR42', 'ADDPRS42', 'PHQ242', 'ADINSA42', 'ADINSB42', 'ADRISK42', 'ADOVER42', 'ADILCR42', 'ADILWW42', 'ADRTCR42', 'ADRTWW42', 'ADAPPT42', 'ADHECR42', 'ADINST42', 'ADEZUN42', 'ADTLHW42', 'ADFFRM42', 'ADFHLP42', 'ADEXPL42', 'ADLIST42', 'ADRESP42', 'ADPRTM42', 'ADSMOK42', 'ADNSMK42', 'ADSPCL42', 'ADSNSP42', 'VPCS42', 'VMCS42', 'VRFLAG42', 'ADCMPM42', 'ADCMPY42', 'ADLANG42', 'DDNWRK23', 'OTHDYS23', 'OTHNDD23', 'ACCELI42', 'HAVEUS42', 'PRACTP42', 'YNOUSC42_M18', 'PROVTY42_M18', 'PLCTYP42', 'TMTKUS42', 'TYPEPE42', 'LOCATN42', 'HSPLAP42', 'WHITPR42', 'BLCKPR42', 'ASIANP42', 'NATAMP42', 'PACISP42', 'OTHRCP42', 'PROVSEX42', 'PHNREG42', 'OFFHOU42', 'AFTHOU42', 'TREATM42', 'DECIDE42', 'EXPLOP42', 'PRVSPK42', 'DLAYCA42', 'AFRDCA42', 'DLAYDN42', 'AFRDDN42', 'DLAYPM42', 'AFRDPM42', 'EMPST31', 'EMPST42', 'EMPST53', 'RNDFLG31', 'MORJOB31', 'MORJOB42', 'MORJOB53', 'EVRWRK', 'HRWG31X', 'HRWG42X', 'HRWG53X', 'HRWGIM31', 'HRWGIM42', 'HRWGIM53', 'HRHOW31', 'HRHOW42', 'HRHOW53', 'DIFFWG31', 'DIFFWG42', 'DIFFWG53', 'NHRWGRND31', 'NHRWGRND42', 'NHRWGRND53', 'NHRWG31_M23', 'NHRWG42_M23', 'NHRWG53_M23', 'HOUR31', 'HOUR42', 'HOUR53', 'TEMPJB31', 'TEMPJB42', 'TEMPJB53', 'SSNLJB31', 'SSNLJB42', 'SSNLJB53', 'SELFCM31', 'SELFCM42', 'SELFCM53', 'DISVW31X', 'DISVW42X', 'DISVW53X', 'CHOIC31', 'CHOIC42', 'CHOIC53', 'INDCAT31', 'INDCAT31_17', 'INDCAT42_17', 'INDCAT53_17', 'NUMEMP31', 'NUMEMP42', 'NUMEMP53', 'MORE31', 'MORE42', 'MORE53', 'UNION31', 'UNION42', 'UNION53', 'NWK31', 'NWK42', 'NWK53', 'CHGJ3142', 'CHGJ4253', 'YCHJ3142', 'YCHJ4253', 'STJBMM31', 'STJBYY31', 'STJBMM42', 'STJBYY42', 'STJBMM53', 'STJBYY53', 'EVRETIRE', 'OCCCAT31', 'OCCCAT31_18', 'OCCCAT42_18', 'OCCCAT53_18', 'PAYVAC31', 'PAYVAC42', 'PAYVAC53', 'SICPAY31', 'SICPAY42', 'SICPAY53', 'PAYDR31', 'PAYDR42', 'PAYDR53', 'RETPLN31', 'RETPLN42', 'RETPLN53', 'BSNTY31', 'BSNTY42', 'BSNTY53', 'JOBORG31', 'JOBORG42', 'JOBORG53', 'HELD31X', 'HELD42X', 'HELD53X', 'OFFER31X', 'OFFER42X', 'OFFER53X', 'OFREMP31', 'OFREMP42', 'OFREMP53', 'EMPST31H', 'EMPST42H', 'EMPST53H', 'SLFCM31H', 'SLFCM42H', 'SLFCM53H', 'NMEMP31H', 'NMEMP42H', 'NMEMP53H', 'MORE31H', 'MORE42H', 'MORE53H', 'INDCT31H', 'INDCT31H_17', 'INDCT42H_17', 'INDCT53H_17', 'OCCCT31H', 'OCCCT31H_18', 'OCCCT42H_18', 'OCCCT53H_18', 'HOUR31H', 'HOUR42H', 'HOUR53H', 'JBORG31H', 'JBORG42H', 'JBORG53H', 'UNION31H', 'UNION42H', 'UNION53H', 'BSNTY31H', 'BSNTY42H', 'BSNTY53H', 'HRWG31H', 'HRWG42H', 'HRWG53H', 'CMJHLD31', 'CMJHLD42', 'CMJHLD53', 'OFFER31H', 'OFFER42H', 'OFFER53H', 'OFEMP31H', 'OFEMP42H', 'OFEMP53H', 'PYVAC31H', 'PYVAC42H', 'PYVAC53H', 'SCPAY31H', 'SCPAY42H', 'SCPAY53H', 'PAYDR31H', 'PAYDR42H', 'PAYDR53H', 'RTPLN31H', 'RTPLN42H', 'RTPLN53H', 'FILEDR23', 'WILFIL23', 'FLSTAT23', 'FILER23', 'JTINRU23', 'JNTPID23', 'TAXFRM23', 'FOODST23', 'FOODMN23', 'FOODVL23', 'TTLP23X', 'FAMINC23', 'POVCAT23', 'POVLEV23', 'WAGEP23X', 'WAGIMP23', 'BUSNP23X', 'BUSIMP23', 'UNEMP23X', 'UNEIMP23', 'WCMPP23X', 'WCPIMP23', 'INTRP23X', 'INTIMP23', 'DIVDP23X', 'DIVIMP23', 'SALEP23X', 'SALIMP23', 'PENSP23X', 'PENIMP23', 'SSECP23X', 'SSCIMP23', 'TRSTP23X', 'TRTIMP23', 'VETSP23X', 'VETIMP23', 'IRASP23X', 'IRAIMP23', 'ALIMP23X', 'ALIIMP23', 'CHLDP23X', 'CHLIMP23', 'CASHP23X', 'CSHIMP23', 'SSIP23X', 'SSIIMP23', 'PUBP23X', 'PUBIMP23', 'OTHRP23X', 'OTHIMP23', 'HIEUIDX', 'TRIJA23X', 'TRIFE23X', 'TRIMA23X', 'TRIAP23X', 'TRIMY23X', 'TRIJU23X', 'TRIJL23X', 'TRIAU23X', 'TRISE23X', 'TRIOC23X', 'TRINO23X', 'TRIDE23X', 'MCRJA23', 'MCRFE23', 'MCRMA23', 'MCRAP23', 'MCRMY23', 'MCRJU23', 'MCRJL23', 'MCRAU23', 'MCRSE23', 'MCROC23', 'MCRNO23', 'MCRDE23', 'MCRJA23X', 'MCRFE23X', 'MCRMA23X', 'MCRAP23X', 'MCRMY23X', 'MCRJU23X', 'MCRJL23X', 'MCRAU23X', 'MCRSE23X', 'MCROC23X', 'MCRNO23X', 'MCRDE23X', 'MCDJA23', 'MCDFE23', 'MCDMA23', 'MCDAP23', 'MCDMY23', 'MCDJU23', 'MCDJL23', 'MCDAU23', 'MCDSE23', 'MCDOC23', 'MCDNO23', 'MCDDE23', 'MCDJA23X', 'MCDFE23X', 'MCDMA23X', 'MCDAP23X', 'MCDMY23X', 'MCDJU23X', 'MCDJL23X', 'MCDAU23X', 'MCDSE23X', 'MCDOC23X', 'MCDNO23X', 'MCDDE23X', 'GVAJA23', 'GVAFE23', 'GVAMA23', 'GVAAP23', 'GVAMY23', 'GVAJU23', 'GVAJL23', 'GVAAU23', 'GVASE23', 'GVAOC23', 'GVANO23', 'GVADE23', 'GVBJA23', 'GVBFE23', 'GVBMA23', 'GVBAP23', 'GVBMY23', 'GVBJU23', 'GVBJL23', 'GVBAU23', 'GVBSE23', 'GVBOC23', 'GVBNO23', 'GVBDE23', 'GVCJA23', 'GVCFE23', 'GVCMA23', 'GVCAP23', 'GVCMY23', 'GVCJU23', 'GVCJL23', 'GVCAU23', 'GVCSE23', 'GVCOC23', 'GVCNO23', 'GVCDE23', 'VAPJA23', 'VAPFE23', 'VAPMA23', 'VAPAP23', 'VAPMY23', 'VAPJU23', 'VAPJL23', 'VAPAU23', 'VAPSE23', 'VAPOC23', 'VAPNO23', 'VAPDE23', 'IHSJA23', 'IHSFE23', 'IHSMA23', 'IHSAP23', 'IHSMY23', 'IHSJU23', 'IHSJL23', 'IHSAU23', 'IHSSE23', 'IHSOC23', 'IHSNO23', 'IHSDE23', 'PUBJA23X', 'PUBFE23X', 'PUBMA23X', 'PUBAP23X', 'PUBMY23X', 'PUBJU23X', 'PUBJL23X', 'PUBAU23X', 'PUBSE23X', 'PUBOC23X', 'PUBNO23X', 'PUBDE23X', 'PEGJA23', 'PEGFE23', 'PEGMA23', 'PEGAP23', 'PEGMY23', 'PEGJU23', 'PEGJL23', 'PEGAU23', 'PEGSE23', 'PEGOC23', 'PEGNO23', 'PEGDE23', 'PDKJA23', 'PDKFE23', 'PDKMA23', 'PDKAP23', 'PDKMY23', 'PDKJU23', 'PDKJL23', 'PDKAU23', 'PDKSE23', 'PDKOC23', 'PDKNO23', 'PDKDE23', 'PNGJA23', 'PNGFE23', 'PNGMA23', 'PNGAP23', 'PNGMY23', 'PNGJU23', 'PNGJL23', 'PNGAU23', 'PNGSE23', 'PNGOC23', 'PNGNO23', 'PNGDE23', 'POGJA23', 'POGFE23', 'POGMA23', 'POGAP23', 'POGMY23', 'POGJU23', 'POGJL23', 'POGAU23', 'POGSE23', 'POGOC23', 'POGNO23', 'POGDE23', 'POEJA23', 'POEFE23', 'POEMA23', 'POEAP23', 'POEMY23', 'POEJU23', 'POEJL23', 'POEAU23', 'POESE23', 'POEOC23', 'POENO23', 'POEDE23', 'PNEJA23', 'PNEFE23', 'PNEMA23', 'PNEAP23', 'PNEMY23', 'PNEJU23', 'PNEJL23', 'PNEAU23', 'PNESE23', 'PNEOC23', 'PNENO23', 'PNEDE23', 'PRXJA23', 'PRXFE23', 'PRXMA23', 'PRXAP23', 'PRXMY23', 'PRXJU23', 'PRXJL23', 'PRXAU23', 'PRXSE23', 'PRXOC23', 'PRXNO23', 'PRXDE23', 'PRIJA23', 'PRIFE23', 'PRIMA23', 'PRIAP23', 'PRIMY23', 'PRIJU23', 'PRIJL23', 'PRIAU23', 'PRISE23', 'PRIOC23', 'PRINO23', 'PRIDE23', 'HPEJA23', 'HPEFE23', 'HPEMA23', 'HPEAP23', 'HPEMY23', 'HPEJU23', 'HPEJL23', 'HPEAU23', 'HPESE23', 'HPEOC23', 'HPENO23', 'HPEDE23', 'HPDJA23', 'HPDFE23', 'HPDMA23', 'HPDAP23', 'HPDMY23', 'HPDJU23', 'HPDJL23', 'HPDAU23', 'HPDSE23', 'HPDOC23', 'HPDNO23', 'HPDDE23', 'HPNJA23', 'HPNFE23', 'HPNMA23', 'HPNAP23', 'HPNMY23', 'HPNJU23', 'HPNJL23', 'HPNAU23', 'HPNSE23', 'HPNOC23', 'HPNNO23', 'HPNDE23', 'HPOJA23', 'HPOFE23', 'HPOMA23', 'HPOAP23', 'HPOMY23', 'HPOJU23', 'HPOJL23', 'HPOAU23', 'HPOSE23', 'HPOOC23', 'HPONO23', 'HPODE23', 'HPXJA23', 'HPXFE23', 'HPXMA23', 'HPXAP23', 'HPXMY23', 'HPXJU23', 'HPXJL23', 'HPXAU23', 'HPXSE23', 'HPXOC23', 'HPXNO23', 'HPXDE23', 'HPRJA23', 'HPRFE23', 'HPRMA23', 'HPRAP23', 'HPRMY23', 'HPRJU23', 'HPRJL23', 'HPRAU23', 'HPRSE23', 'HPROC23', 'HPRNO23', 'HPRDE23', 'INSJA23X', 'INSFE23X', 'INSMA23X', 'INSAP23X', 'INSMY23X', 'INSJU23X', 'INSJL23X', 'INSAU23X', 'INSSE23X', 'INSOC23X', 'INSNO23X', 'INSDE23X', 'PRVEV23', 'TRIEV23', 'MCREV23', 'MCDEV23', 'VAEV23', 'GVAEV23', 'GVBEV23', 'GVCEV23', 'UNINS23', 'INSCOV23', 'INSURC23', 'TRICH31X', 'TRICH42X', 'TRICH23X', 'TRI31X', 'TRI42X', 'TRI23X', 'MCRPHD31', 'MCRPHD42', 'MCRPHD23', 'MCRPD31', 'MCRPD42', 'MCRPD23', 'MCRPD31X', 'MCRPD42X', 'MCRPD23X', 'MCRPHO31', 'MCRPHO42', 'MCRPHO23', 'MCDHMO31', 'MCDHMO42', 'MCDHMO23', 'MCDMC31', 'MCDMC42', 'MCDMC23', 'PRVHMO31_M23', 'PRVHMO42_M23', 'PRVHMO23_M23', 'FSAGT31', 'HASFSA31', 'PFSAMT31', 'PREVCOVR', 'MORECOVR', 'TRICR31X', 'TRICR42X', 'TRICR53X', 'TRICR23X', 'TRIAT31X', 'TRIAT42X', 'TRIAT53X', 'TRIAT23X', 'MCAID31', 'MCAID42', 'MCAID53', 'MCAID23', 'MCAID31X', 'MCAID42X', 'MCAID53X', 'MCAID23X', 'MCARE31', 'MCARE42', 'MCARE53', 'MCARE23', 'MCARE31X', 'MCARE42X', 'MCARE53X', 'MCARE23X', 'MCDAT31X', 'MCDAT42X', 'MCDAT53X', 'MCDAT23X', 'GOVTA31', 'GOVTA42', 'GOVTA53', 'GOVTA23', 'GOVAAT31', 'GOVAAT42', 'GOVAAT53', 'GOVAAT23', 'GOVTB31', 'GOVTB42', 'GOVTB53', 'GOVTB23', 'GOVBAT31', 'GOVBAT42', 'GOVBAT53', 'GOVBAT23', 'GOVTC31', 'GOVTC42', 'GOVTC53', 'GOVTC23', 'GOVCAT31', 'GOVCAT42', 'GOVCAT53', 'GOVCAT23', 'VAPROG31', 'VAPROG42', 'VAPROG53', 'VAPROG23', 'VAPRAT31', 'VAPRAT42', 'VAPRAT53', 'VAPRAT23', 'IHS31', 'IHS42', 'IHS53', 'IHS23', 'IHSAT31', 'IHSAT42', 'IHSAT53', 'IHSAT23', 'PRIDK31', 'PRIDK42', 'PRIDK53', 'PRIDK23', 'PRIEU31', 'PRIEU42', 'PRIEU53', 'PRIEU23', 'PRING31', 'PRING42', 'PRING53', 'PRING23', 'PRIOG31', 'PRIOG42', 'PRIOG53', 'PRIOG23', 'PRINEO31', 'PRINEO42', 'PRINEO53', 'PRINEO23', 'PRIEUO31', 'PRIEUO42', 'PRIEUO53', 'PRIEUO23', 'PRSTX31', 'PRSTX42', 'PRSTX53', 'PRSTX23', 'PRIV31', 'PRIV42', 'PRIV53', 'PRIV23', 'PRIVAT31', 'PRIVAT42', 'PRIVAT53', 'PRIVAT23', 'PUB31X', 'PUB42X', 'PUB53X', 'PUB23X', 'PUBAT31X', 'PUBAT42X', 'PUBAT53X', 'PUBAT23X', 'VERFLG31', 'VERFLG42', 'VERFLG23', 'INS31X', 'INS42X', 'INS53X', 'INS23X', 'INSAT31X', 'INSAT42X', 'INSAT53X', 'INSAT23X', 'DENTIN31_M23', 'DENTIN42_M23', 'DENTIN53_M23', 'DNTINS31_M23', 'DNTINS23_M23', 'PMEDIN31', 'PMEDIN42', 'PMEDIN53', 'PMDINS31', 'PMDINS23', 'PROBPY42', 'CRFMPY42', 'PYUNBL42', 'PMEDUP31', 'PMEDUP42', 'PMEDUP53', 'PMEDPY31', 'PMEDPY42', 'PMEDPY53', 'TOTTCH23', 'TOTEXP23', 'TOTSLF23', 'TOTMCR23', 'TOTMCD23', 'TOTPRV23', 'TOTVA23', 'TOTTRI23', 'TOTOFD23', 'TOTSTL23', 'TOTWCP23', 'TOTOSR23', 'TOTPTR23', 'TOTOTH23', 'OBTOTV23', 'OBVTCH23', 'OBVEXP23', 'OBVSLF23', 'OBVMCR23', 'OBVMCD23', 'OBVPRV23', 'OBVVA23', 'OBVTRI23', 'OBVOFD23', 'OBVSTL23', 'OBVWCP23', 'OBVOSR23', 'OBVPTR23', 'OBVOTH23', 'OBDRV23', 'OBDTCH23', 'OBDEXP23', 'OBDSLF23', 'OBDMCR23', 'OBDMCD23', 'OBDPRV23', 'OBDVA23', 'OBDTRI23', 'OBDOFD23', 'OBDSTL23', 'OBDWCP23', 'OBDOSR23', 'OBDPTR23', 'OBDOTH23', 'OPTOTV23', 'OPTTCH23', 'OPTEXP23', 'OPTSLF23', 'OPTMCR23', 'OPTMCD23', 'OPTPRV23', 'OPTVA23', 'OPTTRI23', 'OPTOFD23', 'OPTSTL23', 'OPTWCP23', 'OPTOSR23', 'OPTPTR23', 'OPTOTH23', 'OPFTCH23', 'OPFEXP23', 'OPFSLF23', 'OPFMCR23', 'OPFMCD23', 'OPFPRV23', 'OPFVA23', 'OPFTRI23', 'OPFOFD23', 'OPFSTL23', 'OPFWCP23', 'OPFOSR23', 'OPFPTR23', 'OPFOTH23', 'OPDEXP23', 'OPDTCH23', 'OPDSLF23', 'OPDMCR23', 'OPDMCD23', 'OPDPRV23', 'OPDVA23', 'OPDTRI23', 'OPDOFD23', 'OPDSTL23', 'OPDWCP23', 'OPDOSR23', 'OPDPTR23', 'OPDOTH23', 'OPDRV23', 'OPVTCH23', 'OPVEXP23', 'OPVSLF23', 'OPVMCR23', 'OPVMCD23', 'OPVPRV23', 'OPVVA23', 'OPVTRI23', 'OPVOFD23', 'OPVSTL23', 'OPVWCP23', 'OPVOSR23', 'OPVPTR23', 'OPVOTH23', 'OPSEXP23', 'OPSTCH23', 'OPSSLF23', 'OPSMCR23', 'OPSMCD23', 'OPSPRV23', 'OPSVA23', 'OPSTRI23', 'OPSOFD23', 'OPSSTL23', 'OPSWCP23', 'OPSOSR23', 'OPSPTR23', 'OPSOTH23', 'ERTOT23', 'ERTTCH23', 'ERTEXP23', 'ERTSLF23', 'ERTMCR23', 'ERTMCD23', 'ERTPRV23', 'ERTVA23', 'ERTTRI23', 'ERTOFD23', 'ERTSTL23', 'ERTWCP23', 'ERTOSR23', 'ERTPTR23', 'ERTOTH23', 'ERFTCH23', 'ERFEXP23', 'ERFSLF23', 'ERFMCR23', 'ERFMCD23', 'ERFPRV23', 'ERFVA23', 'ERFTRI23', 'ERFOFD23', 'ERFSTL23', 'ERFWCP23', 'ERFOSR23', 'ERFPTR23', 'ERFOTH23', 'ERDEXP23', 'ERDTCH23', 'ERDSLF23', 'ERDMCR23', 'ERDMCD23', 'ERDPRV23', 'ERDVA23', 'ERDTRI23', 'ERDOFD23', 'ERDSTL23', 'ERDWCP23', 'ERDOSR23', 'ERDPTR23', 'ERDOTH23', 'IPDIS23', 'IPTEXP23', 'IPTTCH23', 'IPTSLF23', 'IPTMCR23', 'IPTMCD23', 'IPTPRV23', 'IPTVA23', 'IPTTRI23', 'IPTOFD23', 'IPTSTL23', 'IPTWCP23', 'IPTOSR23', 'IPTPTR23', 'IPTOTH23', 'IPFEXP23', 'IPFTCH23', 'IPFSLF23', 'IPFMCR23', 'IPFMCD23', 'IPFPRV23', 'IPFVA23', 'IPFTRI23', 'IPFOFD23', 'IPFSTL23', 'IPFWCP23', 'IPFOSR23', 'IPFPTR23', 'IPFOTH23', 'IPDEXP23', 'IPDTCH23', 'IPDSLF23', 'IPDMCR23', 'IPDMCD23', 'IPDPRV23', 'IPDVA23', 'IPDTRI23', 'IPDOFD23', 'IPDSTL23', 'IPDWCP23', 'IPDOSR23', 'IPDPTR23', 'IPDOTH23', 'IPNGTD23', 'DVTOT23', 'DVTTCH23', 'DVTEXP23', 'DVTSLF23', 'DVTMCR23', 'DVTMCD23', 'DVTPRV23', 'DVTVA23', 'DVTTRI23', 'DVTOFD23', 'DVTSTL23', 'DVTWCP23', 'DVTOSR23', 'DVTPTR23', 'DVTOTH23', 'HHTOTD23', 'HHAGD23', 'HHATCH23', 'HHAEXP23', 'HHASLF23', 'HHAMCR23', 'HHAMCD23', 'HHAPRV23', 'HHAVA23', 'HHATRI23', 'HHAOFD23', 'HHASTL23', 'HHAWCP23', 'HHAOSR23', 'HHAPTR23', 'HHAOTH23', 'HHINDD23', 'HHNTCH23', 'HHNEXP23', 'HHNSLF23', 'HHNMCD23', 'HHNMCR23', 'HHNPRV23', 'HHNVA23', 'HHNTRI23', 'HHNOFD23', 'HHNSTL23', 'HHNWCP23', 'HHNOSR23', 'HHNPTR23', 'HHNOTH23', 'HHINFD23', 'VISEXP23', 'VISTCH23', 'VISSLF23', 'VISMCR23', 'VISMCD23', 'VISPRV23', 'VISVA23', 'VISTRI23', 'VISOFD23', 'VISSTL23', 'VISWCP23', 'VISOSR23', 'VISPTR23', 'VISOTH23', 'OTHTCH23', 'OTHEXP23', 'OTHSLF23', 'OTHMCR23', 'OTHMCD23', 'OTHPRV23', 'OTHVA23', 'OTHTRI23', 'OTHOFD23', 'OTHSTL23', 'OTHWCP23', 'OTHOSR23', 'OTHPTR23', 'OTHOTH23', 'RXTOT23', 'RXEXP23', 'RXSLF23', 'RXMCR23', 'RXMCD23', 'RXPRV23', 'RXVA23', 'RXTRI23', 'RXOFD23', 'RXSTL23', 'RXWCP23', 'RXOSR23', 'RXPTR23', 'RXOTH23', 'PERWT23F', 'FAMWT23F', 'FAMWT23C', 'SAQWT23F', 'VARSTR', 'VARPSU']

# Total Rows, Null Columns & Total Size

In [84]:
# print(f"h243 shape: {data_h243.shape} \n")
# data_h243.info()
# h243_null_values = data_h243.isna().sum()

# print(f"null values present?: {data_h243.isna().values.any()}")
# print(f"\nh243 null values:\n{h243_null_values[h243_null_values > 0]}")
# print(f"\nh243 describe:\n{data_h243.describe(include='all')}")

# print("\n" + "===="* 10 + "\n")

print(f"h251 shape: {data_h251.shape} \n")
data_h251.info()
h251_null_values = data_h251.isna().sum()
print(f"null values present?: {data_h251.isna().values.any()}")
print(f"\nh251 null values:\n{h251_null_values[h251_null_values > 0]}")
print(f"\nh251 describe:\n{data_h251.describe(include='all')}")

h251 shape: (18919, 1374)

<class 'pandas.DataFrame'>
RangeIndex: 18919 entries, 0 to 18918
Columns: 1374 entries, DUID to VARPSU
dtypes: float64(16), int64(1347), str(11)
memory usage: 198.3 MB
null values present?: False

h251 null values:
Series([], dtype: int64)

h251 describe:
                DUID           PID      DUPERSID         PANEL  DATAYEAR  \
count   1.891900e+04  18919.000000  1.891900e+04  18919.000000   18919.0
unique           NaN           NaN           NaN           NaN       NaN
top              NaN           NaN           NaN           NaN       NaN
freq             NaN           NaN           NaN           NaN       NaN
mean    2.805930e+06    102.581902  2.805930e+09     27.554205    2023.0
std     1.035167e+04      7.791801  1.035167e+07      0.497066       0.0
min     2.790002e+06    101.000000  2.790002e+09     27.000000    2023.0
25%     2.795372e+06    101.000000  2.795373e+09     27.000000    2023.0
50%     2.810894e+06    102.000000  2.810894e+09     28.000000    2023.0
75%     2.815367e+06    103.000000  2.815367e+09     28.000000    2023.0
max     2.819793e+06    401.000000  2.819793e+09     28.000000    2023.0

       FAMID31 FAMID42 FAMID53 FAMID23 FAMIDYR  ...       RXWCP23  \
count    18919   18919   18919   18919   18919  ...  18919.000000
unique       8       8       8       8       7  ...           NaN
top          A       A       A       A       A  ...           NaN
freq     18158   18170   18124   18124   18273  ...           NaN
mean       NaN     NaN     NaN     NaN     NaN  ...      0.171521
std        NaN     NaN     NaN     NaN     NaN  ...      8.748251
min        NaN     NaN     NaN     NaN     NaN  ...      0.000000
25%        NaN     NaN     NaN     NaN     NaN  ...      0.000000
50%        NaN     NaN     NaN     NaN     NaN  ...      0.000000
75%        NaN     NaN     NaN     NaN     NaN  ...      0.000000
max        NaN     NaN     NaN     NaN     NaN  ...    947.000000

             RXOSR23        RXPTR23       RXOTH23       PERWT23F  \
count   18919.000000   18919.000000  18919.000000   18919.000000
unique           NaN            NaN           NaN            NaN
top              NaN            NaN           NaN            NaN
freq             NaN            NaN           NaN            NaN
mean        0.190232     733.879645     21.146097   17682.238658
std        19.103557    6806.028931    656.588319   12672.379959
min         0.000000       0.000000      0.000000       0.000000
25%         0.000000       0.000000      0.000000    9547.229001
50%         0.000000       0.000000      0.000000   14788.741260
75%         0.000000       0.000000      0.000000   22543.992365
max      2552.000000  370634.000000  66667.000000  131656.577000

             FAMWT23F       FAMWT23C       SAQWT23F        VARSTR  \
count    18919.000000   18919.000000   18919.000000  18919.000000
unique            NaN            NaN            NaN           NaN
top               NaN            NaN            NaN           NaN
freq              NaN            NaN            NaN           NaN
mean     17170.225666   16962.532138   13659.647020   2055.909192
std      13620.400183   13717.537133   20504.706095     34.322730
min          0.000000       0.000000       0.000000   2001.000000
25%       8610.457435    8343.432437       0.000000   2026.000000
50%      14427.443870   14293.301080    4472.718173   2055.000000
75%      22689.668230   22587.745230   20881.742085   2087.000000
max     134738.479100  134738.479100  212566.867300   2117.000000

              VARPSU
count   18919.000000
unique           NaN
top              NaN
freq             NaN
mean        1.978276
std         1.033994
min         1.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         6.000000

[11 rows x 1374 columns]

In [85]:

# h243_unique_counts = data_h243.nunique()
# print(h243_unique_counts)

# print("\n" + "===="* 10 + "\n")

h251_unique_counts = data_h251.nunique()
print(h251_unique_counts)

DUID         8914
PID            24
DUPERSID    18919
PANEL           2
DATAYEAR        1
            ...
FAMWT23F     8113
FAMWT23C     8418
SAQWT23F     9732
VARSTR        105
VARPSU          6
Length: 1374, dtype: int64

# Filter Columns - Most Important

In [86]:
FILTER_COLUMNS = [
    # unique identifiers
    "DUID",
    "PID",
    "DUPERSID",
    "PANEL",
    # protected attributes
    "RACEV1X",
    "RACETHX",
    "HISPANX",
    "SEX",
    # target variables
    "OBTOTV23",
    "OPTOTV23",
    "ERTOT23",
    "IPDIS23",
    "HHTOTD23",
    # demographic/socioeconomic
    "AGE23X",
    "EDUCYR",
    "MARRY53X",
    "POVCAT23",
    "POVLEV23",
    "TTLP23X",
    "INSCOV23",
    "EMPST53",
    "REGION53",
    "BORNUSA",
    "YRSINUS",
    # health
    "RTHLTH53",
    "MNHLTH53",
    "ANYLMI23",
    "PHYEXE53",
    "OFTSMK53",
    "HIBPDX",
    "DIABDX_M18",
    "ARTHDX",
    "JTPAIN31_M18",
    "CANCERDX",
    "ASTHDX",
    "CHDDX",
    "OHRTDX",
    "STRKDX",
    "CHOLDX",
    "EMPHDX",
    "CHBRON31",
    "RXTOT23",
    "PERWT23F",
    # access to care
    "HAVEUS42",
    "TYPEPE42",
    "AFRDCA42",
    "AFRDPM42",
    # costs/expenses
    "TOTEXP23",
    "TOTSLF23",
    # stats
    "VARSTR",
    "VARPSU"
]

print(f"h251 columns len: {len(data_h251.columns)}")
print(f"h251 filtered columns len: {len(FILTER_COLUMNS)}")
print(f"number of h251 discarded columns: {len(data_h251.columns) - len(FILTER_COLUMNS)}")

print("\n" + "===="* 10 + "\n")

h251_filtered = data_h251[FILTER_COLUMNS]
display(h251_filtered.head())

print("\n" + "===="* 10 + "\n")

print(f"\nh251 filtered shape: {h251_filtered.shape}")

h251 columns len: 1374
h251 filtered columns len: 51
number of h251 discarded columns: 1323

========================================

,DUID,PID,DUPERSID,PANEL,RACEV1X,RACETHX,HISPANX,SEX,OBTOTV23,OPTOTV23,...,RXTOT23,PERWT23F,HAVEUS42,TYPEPE42,AFRDCA42,AFRDPM42,TOTEXP23,TOTSLF23,VARSTR,VARPSU
0,2790002,101,2790002101,27,2,3,2,2,3,1,...,9,11664.42682,1,12,2,2,646,189,2019,1
1,2790002,102,2790002102,27,2,3,2,1,1,0,...,0,32212.11360,2,-1,2,2,1894,400,2019,1
2,2790004,101,2790004101,27,1,2,2,2,1,0,...,0,21944.14283,1,12,2,2,986,10,2084,1
3,2790006,101,2790006101,27,1,2,2,2,3,0,...,26,10328.00953,1,-1,2,2,1312,191,2113,1
4,2790006,102,2790006102,27,1,2,2,1,0,0,...,0,17430.52136,2,-1,2,2,0,0,2113,1

========================================


h251 filtered shape: (18919, 51)

In [ ]:
NULL_VALUES = [-1, -7, -8, -9, -15]

h251 = h251_filtered.replace(NULL_VALUES, np.nan).copy()

check_null_values = (h251.select_dtypes("number") < 0).sum().sum()
print(f"null values present?: {check_null_values > 0}")
print(f"null values count: {check_null_values}")
print(f"null values count after replacement: {h251.isnull().sum().sum():,}")

# print("\n" + "===="* 10 + "\n")

# """after checking output is ok to keep them"""
# num_cols = h251.select_dtypes("number").columns
# print("rest negative per column:")
# for col in num_cols:
#     negs = h251[col][h251[col] < 0].unique()
#     if len(negs) > 0:
#         print(f"  {col:<25} {sorted(negs)}")

null values present?: True
null values count: 4
null values count after replacement: 83,809

========================================

rest negative per column:
  POVLEV23                  [np.float64(-1.57)]
  TTLP23X                   [np.int64(-23290), np.int64(-1500), np.int64(-230)]

# Clean Columns

In [93]:
na_values_columns = h251.isnull().mean().sort_values(ascending=False)

print("mean of null values per column:")
for col, mean in na_values_columns.items():
    flag = ""
    if mean > 0.5:
        flag = " --> high null values"
    elif mean > 0.2:
        flag = " --> moderate null values"
    
    if mean > 0:
        print(f"  {col:<25} {mean:.2%}{flag}")

mean of null values per column:
  YRSINUS                   83.72% --> high null values
  TYPEPE42                  48.03% --> moderate null values
  JTPAIN31_M18              42.76% --> moderate null values
  CHBRON31                  21.71% --> moderate null values
  PHYEXE53                  21.52% --> moderate null values
  OFTSMK53                  21.16% --> moderate null values
  CHOLDX                    20.14% --> moderate null values
  HIBPDX                    20.08% --> moderate null values
  ARTHDX                    20.08% --> moderate null values
  CANCERDX                  20.04% --> moderate null values
  CHDDX                     20.04% --> moderate null values
  OHRTDX                    20.03% --> moderate null values
  STRKDX                    20.02% --> moderate null values
  EMPHDX                    20.02% --> moderate null values
  EMPST53                   18.51%
  EDUCYR                    6.37%
  HAVEUS42                  5.31%
  ANYLMI23                  2.83%
  AFRDCA42                  1.69%
  AFRDPM42                  1.63%
  MNHLTH53                  1.45%
  RTHLTH53                  1.45%
  MARRY53X                  0.89%
  AGE23X                    0.78%
  REGION53                  0.78%
  ASTHDX                    0.62%
  DIABDX_M18                0.61%
  BORNUSA                   0.37%
  HHTOTD23                  0.34%

In [102]:
CHRONIC_DISEASES = [
    "HIBPDX",
    "DIABDX_M18",
    "ARTHDX",
    "JTPAIN31_M18",
    "CANCERDX",
    "ASTHDX",
    "CHDDX",
    "OHRTDX",
    "STRKDX",
    "CHOLDX",
    "EMPHDX",
    "CHBRON31"
]

"""recode values 1 to 1 (yes) and 2 to 0 (no) for chronic diseases"""
for col in CHRONIC_DISEASES:
    if col in h251.columns:
        h251[col] = h251[col].map({1: 1, 2: 0})

for col in CHRONIC_DISEASES:
    if col in h251.columns:
        unique_values = h251[col].dropna().unique()
        mean_val = h251[col].mean()
        print(f"{col:<15} unique values: {unique_values} | mean: {mean_val:.1%}")

HIBPDX          unique values: [1.] | mean: 100.0%
DIABDX_M18      unique values: [1.] | mean: 100.0%
ARTHDX          unique values: [1.] | mean: 100.0%
JTPAIN31_M18    unique values: [1.] | mean: 100.0%
CANCERDX        unique values: [1.] | mean: 100.0%
ASTHDX          unique values: [1.] | mean: 100.0%
CHDDX           unique values: [1.] | mean: 100.0%
OHRTDX          unique values: [1.] | mean: 100.0%
STRKDX          unique values: [1.] | mean: 100.0%
CHOLDX          unique values: [1.] | mean: 100.0%
EMPHDX          unique values: [1.] | mean: 100.0%
CHBRON31        unique values: [1.] | mean: 100.0%

# Target Variable

In [110]:
TARGETS = ["OBTOTV23", "OPTOTV23", "ERTOT23", "IPDIS23", "HHTOTD23"]

h251["TOTAL_VISITS"] = h251[TARGETS].fillna(0).clip(lower=0).sum(axis=1)
h251["HIGH_UTIL"] = (h251["TOTAL_VISITS"] >= 10).astype(int)

print(f"total persons: {len(h251)}")
print(f"high utilisation >= 10 visits: {h251['HIGH_UTIL'].sum()} ({h251['HIGH_UTIL'].mean():.1%})")
print(f"low utilisation < 10 visits: {(h251['HIGH_UTIL']==0).sum()} ({(h251['HIGH_UTIL']==0).mean():.1%})")

print("\n" + "===="* 10 + "\n")

print(f"stats total visits:\n\n {h251['TOTAL_VISITS'].describe()}")

total persons: 18919
high utilisation >= 10 visits: 5092 (26.9%)
low utilisation < 10 visits: 13827 (73.1%)

========================================

stats total visits:

 count    18919.000000
mean        11.968392
std         33.108895
min          0.000000
25%          1.000000
50%          3.000000
75%         10.000000
max        771.000000
Name: TOTAL_VISITS, dtype: float64